- name: Create Jenkins Jobs
  hosts: localhost
  become: true
  roles:
    - jenkins
  vars:
    folders:
      - { folder_name: "CI-Pipelines" }
      - { folder_name: "Infra-Jobs" }
      - { folder_name: "Deployment" }
    mjobs:
      - { job_name: "cart", repo_name: "https://github.com/abhijeet4022/cart-v1", folder_name: "CI-Pipelines" }
      - { job_name: "catalogue", repo_name: "https://github.com/abhijeet4022/catalogue-v1", folder_name: "CI-Pipelines" }
      - { job_name: "user", repo_name: "https://github.com/abhijeet4022/user-v1", folder_name: "CI-Pipelines" }
      - { job_name: "shipping", repo_name: "https://github.com/abhijeet4022/shipping-v1", folder_name: "CI-Pipelines" }
      - { job_name: "payment", repo_name: "https://github.com/abhijeet4022/payment-v1", folder_name: "CI-Pipelines" }
      - { job_name: "frontend", repo_name: "https://github.com/abhijeet4022/frontend-v1", folder_name: "CI-Pipelines" }
      - { job_name: "init-container", repo_name: "https://github.com/abhijeet4022/project-init-cont", folder_name: "CI-Pipelines" }
    sjobs:
      - { job_name: "roboshop-infra", repo_name: "https://github.com/abhijeet4022/project-infra", folder_name: "Infra-Jobs" }
      - { job_name: "app-deployment", repo_name: "https://github.com/abhijeet4022/project-ansible-deployment", folder_name: "Deployment" }
      - { job_name: "helm-deployment", repo_name: "https://github.com/abhijeet4022/project-helm", folder_name: "Deployment" }