- name: Copy the config file.
  ansible.builtin.template:
    src: folder.xml
    dest: "/tmp/folder.xml"

- name: Create Folder  - {{item.folder_name}}.
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.folder_name}}"
    password: admin
    url: http://172.31.81.162:8080
    user: admin