- name: Create Single Branch Pipeline Jobs
  ansible.builtin.include_tasks:
    file: folder.yml
  loop: "{{ folders }}"

- name: Create Single Branch Pipeline Jobs.
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{ sjobs }}"