- name: Copy the config file.
  ansible.builtin.template:
    src: sjob.xml
    dest: "/tmp/sjob.xml"

- name: Create Job  - {{item.job_name}}.
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/sjob.xml') }}"
    name: "{{item.job_name}}"
    password: admin
    url: http://172.31.81.162:8080
    user: admin